language: php

os:   linux
dist: bionic
sudo: required

php:
    - '7.4'

branches:
    only:
        - 5.0

install:
    - >
        docker build
            -t ${DEV_DOCKER_IMAGE_PYTHON}:base
            .deploy/docker/base
    - >
        docker build
            -t ${DEV_DOCKER_IMAGE_PYTHON}:test
            --build-arg BASE_IMAGE=${DEV_DOCKER_IMAGE_PYTHON}:base
            .deploy/docker/test

script:
    - >
        docker run
            --rm
            --name symfony_doc_pt_br
            -v ${PWD}:/var/www
            ${DEV_DOCKER_IMAGE_PYTHON}:test
            make -C _build html

deploy:
    provider:      pages
    skip_cleanup:  true
    github_token:  ${GITHUB_TOKEN}
    local_dir:     _build/html
    target_branch: gh-pages
    on:
        branch: 5.0
